---
title: "Main analysis"
author: "Isabelle Boulangeat"
date: "02/05/2018"
output: 
  html_document:
      keep_md: yes
      theme: cosmo
      highlight: tango
      number_sections: true
      toc: true
---

<!-- library(rmarkdown) -->
<!-- library(knitr) -->
<!-- knit("preference_pR.Rmd", "preference_pR.md") -->

# Set up

## Load model and parameters

```{r}
rm(list=ls())
source("params.r")
source("model_fct.r")
source("plots_article.r")
source("analysis_fct.r")
```

## Libraries

```{r}
library(rootSolve)
library(cluster)
```

# Change preference parameter

```{r}
init.params["pR"] = 0.8
```

# Analysis

## Equilibrium along the gradient

### Vegetation alone
```{r, results='hide'}
calcEq.veg = data.frame(t(eqveg.fct.Vect(1:grad.div, init.params, par.name, par.clim)))
newEq.veg = data.frame(matrix(unlist(calcEq.veg[[1]]), ncol = 4, byrow = T))
colnames(newEq.veg) = c("T", "R", "B", "H")
newEq.veg[,"V"] = 1 - newEq.veg[,"R"] - newEq.veg[,"B"] - newEq.veg[,"T"]
lambdamax.veg = unlist(calcEq.veg[[2]])
reac.veg = unlist(calcEq.veg[[3]])
newEq.veg.h0 = newEq.veg
newEq.veg.h0[,"H"] = 0
newEq.veg.For = newEq.veg[,"T"] + newEq.veg[,"B"]
```

### Vegetation and hrebivores
```{r}
calcEq.all = data.frame(t(eqall.fct.Vect(1:grad.div, init.params, par.name, par.clim, model)))
newEq.all = data.frame(matrix(unlist(calcEq.all[[1]]), ncol = 4, byrow = T))
colnames(newEq.all) = c("T", "R", "B", "H")
newEq.all[,"V"] = 1 - newEq.all[,"R"] - newEq.all[,"B"] - newEq.all[,"T"]
oscillations = data.frame(matrix(unlist(calcEq.all[[2]]), nrow = grad.div, byrow = TRUE))
colnames(oscillations) = c("T", "R", "B", "H")
lambdamax.all = unlist(calcEq.all[[3]])
reac.all = unlist(calcEq.all[[4]])
newEq.all.For = newEq.all[,"T"] + newEq.all[,"B"]
```

### Domiance
```{r}
Smax = which.max(newEq.all[,"R"])
Bmax = which.max(newEq.all[,"B"])
Hmax = which.max(newEq.all[,"H"])
open = newEq.all[,"V"]
dominance = c("T","B", "V")[apply(cbind(newEq.all[,c("T","B")],open), 1, which.max)]
open.veg = newEq.veg[,"V"]
dominance.veg = c("T","B", "V")[apply(cbind(newEq.veg[,c("T","B")],open.veg), 1, which.max)]
O2B = which(dominance=="B") [1]
B2T = which(dominance=="T") [1]
O2B.veg = which(dominance.veg=="B") [1]
B2T.veg = which(dominance.veg=="T") [1]
```

### Equilibrium figure

```{r equilibrium_pR, fig.height=12, fig.width=12, echo=FALSE}
plot_equilibrium()
```

## Transient metrics

```{r}
deltaN.all = deltaN.veg =  rep(NA, 50)
require(cluster)
dd2<-daisy(newEq.all[,-4], metric="euclidean")
dd.veg2 <- daisy(newEq.veg[,-4], metric="euclidean")
for (g in 1:50)
{
deltaN.all[g] = as.matrix(dd2)[g,g+1]
deltaN.veg[g] = as.matrix(dd.veg2)[g,g+1]
}
simu.time = 10000 # max time of simu before reach eq

calcTime.all = calcTime.Vect(1:50, newEq.all, simu.time=10000, woH=FALSE,init.params=init.params, model)
deltaT.all = unlist(calcTime.all[1,])
integraleV.all = unlist(calcTime.all[2,]) 

calcTime.veg = calcTime.Vect(1:50, newEq.veg, simu.time=10000, woH=TRUE, init.params=init.params, model)
deltaT.veg = unlist(calcTime.veg[1,])
integraleV.veg = unlist(calcTime.veg[2,]) 
```

```{r transient_pR, fig.width=10, fig.height=15, echo=FALSE}
plot_transient()
```

## Correlations

```{r}
(cLDt = c(cor(-lambdamax.veg[-1], deltaT.veg, method="spearman"), cor(-lambdamax.all[-1], deltaT.all, method="spearman")) )
cor.test(-lambdamax.veg[-1], deltaT.veg, method="spearman")
cor.test(-lambdamax.all[-1], deltaT.all,  method="spearman")

(cLR = c(cor(-lambdamax.veg[-1], -reac.veg[-1], method="spearman"), cor(-lambdamax.all[-1], -reac.all[-1], method="spearman")) )
cor.test(-lambdamax.veg[-1], -reac.veg[-1], method="spearman")
cor.test(-lambdamax.all[-1], -reac.all[-1], method="spearman")

(cDnSn = c(cor(deltaN.veg, integraleV.veg, method="spearman"), cor(deltaN.all, integraleV.all, method="spearman")) )
cor.test(deltaN.veg, integraleV.veg, method="spearman") 
cor.test(deltaN.all, integraleV.all, method="spearman") 

(cDtSn = c(cor(deltaT.veg, integraleV.veg, method="spearman"), cor(deltaT.all, integraleV.all, method="spearman")) )
cor.test(deltaT.veg, integraleV.veg, method="spearman") 
cor.test(deltaT.all, integraleV.all, method="spearman") 

(cRDt = c(cor(-reac.veg[-1], deltaT.veg, method="spearman"), cor(-reac.all[-1], deltaT.all, method="spearman")) )
cor.test(-reac.veg[-1], deltaT.veg, method="spearman")
cor.test(-reac.all[-1], deltaT.all, method="spearman") 

(cLSn = c(cor(-lambdamax.veg[-1], integraleV.veg, method="spearman"), cor(-lambdamax.all[-1], integraleV.all, method="spearman")) )
cor.test(-lambdamax.veg[-1], integraleV.veg, method="spearman") 
cor.test(-lambdamax.all[-1], integraleV.all, method="spearman") 

(cRSn = c(cor(-reac.veg[-1], integraleV.veg, method="spearman"), cor(-reac.all[-1], integraleV.all, method="spearman")) )
cor.test(-reac.veg[-1], integraleV.veg, method="spearman") # NS
cor.test(-reac.all[-1], integraleV.all, method="spearman") 

(cDnDt = c(cor(deltaN.veg, deltaT.veg, method="spearman"), cor(deltaN.all, deltaT.all, method="spearman")) )
cor.test(deltaN.veg, deltaT.veg, method="spearman") 
cor.test(deltaN.all, deltaT.all, method="spearman") # NS

(cDnL = c(cor(deltaN.veg, -lambdamax.veg[-1], method="spearman"), cor(deltaN.all, -lambdamax.all[-1], method="spearman")) )
cor.test(deltaN.veg, -lambdamax.veg[-1], method="spearman") 
cor.test(deltaN.all, -lambdamax.all[-1], method="spearman") # NS

(cDnR = c(cor(deltaN.veg, -reac.veg[-1], method="spearman"), cor(deltaN.all, -reac.all[-1], method="spearman")) )
cor.test(deltaN.veg, -reac.veg[-1], method="spearman") # NS
cor.test(deltaN.all, -reac.all[-1], method="spearman") # NS
```

```{r correlations_pR, fig.height=9, fig.width=15}
plot_correlations_pR()
```

