<!-- # ---
# title: "Parmeterization"
# author: "Isabelle Boulangeat"
# date: "02/05/2018"
# output:
#   html_document:
#       keep_md: yes
#       theme: cosmo
#       highlight: tango
#       number_sections: true
#       toc: true
# --- -->

<!-- library(rmarkdown) -->
<!-- library(knitr) -->
<!-- knit("Sensitivity_analysis.Rmd", "Sensitivity_analysis.md") -->

# Load model an params

```{r}
rm(list=ls())
source("model_fct.r")
source("analysis_fct.r")
source("plots_article.r")
params =  c(
a0 = 0.05,
dT = 0.004,
dB = 0.05,
c0 = 0.5,
k = .6
)
```

# Equilibrium

```{r}
with(as.list(params),
{
equi_veget(alpha=a0, c = c0, k = k, deltaB = dB, deltaT = dT)
})
```

# Sensivity analysis

## Sampling

```{r}
library(lhs)
set.seed(999)
lhs = randomLHS(10000,5)
parDesign=data.frame(lhs)
parDesign$a0 <- qnorm(lhs[,1], mean=.05, sd=0.01)
parDesign$c0 <- qnorm(lhs[,2], mean=.5, sd=0.1)
parDesign$dT <- 1/(qnorm(lhs[,3], mean=250, sd=50))
parDesign$dB = 1/(qnorm(lhs[,4], mean=250, sd=50))
parDesign$dTdB  = parDesign$dT/parDesign$dB
parDesign$k <- qnorm(lhs[,5], mean=.5, sd=0.1)

parLHS.pars = parDesign[, which(colnames(parDesign)%in%names(params))]
nrow(parLHS.pars)
nrow(unique(parLHS.pars))
summary(parLHS.pars)
```

## Runs

```{r}
eq.veg.SA = matrix(NA, dimnames= list(1:nrow(parLHS.pars), c("T", "S", "B")), ncol =3, nrow = nrow(parLHS.pars) )

for(i in 1:nrow(parLHS.pars))
{
	# if(i%%1000==0) print(i)
res = with(as.list(parLHS.pars[i,]),
{
equi_veget(alpha=a0, c = c0, k = k, deltaB = dB, deltaT = dT)
})
eq.veg.SA[i,] = res
}

head(eq.veg.SA)
```

## Analysis

```{r}
library(randomForest)
forest = eq.veg.SA[,"T"]+eq.veg.SA[,"B"]
dominance = c("T","B","V")[apply(cbind(eq.veg.SA[,-2], 1-forest),1, which.max)]
table(dominance)
mod1 = randomForest(as.factor(dominance)~., data = parDesign[,c("a0","c0","k","dT","dB","dTdB")])
importance(mod1)

open = 1-apply(eq.veg.SA, 1, sum)
mod2 = randomForest(open~., data = parDesign[,c("a0","c0","k","dT","dB","dTdB")])
importance(mod2)
```

## Graphiques

```{r sensitity1, fig=TRUE, echo=FALSE}
plot_sa.a()
```
k is the most important for T/B dominance

```{r sensitivity2, fig=TRUE, echo=FALSE}
plot_sa.b()
```
c is the most important for open dominance

```{r, include=FALSE}
save.image(file="sensivity_analysis.RData")
```
